builders:
    class_analyzing_builder:
        import: 'package:devcontainer_test/builder.dart'
        builder_factories: ['classAnalyzingBuilder']
        build_extensions: {'.dart': ['class_analyzing.g.part']}
        auto_apply: dependents
        build_to: source
        applies_builders: ['source_gen|combining_builder']
