name: devcontainer_test
publish_to: none
environment:
    sdk: '>=2.9.0-13.0.dev <3.0.0'

dependencies:
    analyzer: ^0.39.10
    build: ^1.3.0
    source_gen: ^0.9.5

dev_dependencies:
    build_runner: ^1.10.0
    build_test: ^1.2.0
    source_gen_test: ^0.1.1
    test: ^1.15.1
